### ISSUE TITLE
Can't even join my server.

### ISSUE THREAD

**Issue by itsThumbsy** [EndlessCodeGroup/RPGInventory#98]
I just installed this plugin and I'm trying to get it working. I'm pretty sure I have the resource pack section of the config set wrong, but I'm getting kicked out of my server. It says I haven't enabled resource packs but I have enabled it on my server and in the plugin config. Is it possible for people to decline the resource pack and not get kicked? Or are resource packs either on or off. 

resource-pack:
  enabled: true
  delay: 2
  url: https://cloud.endlesscode.ru/s/kJYMpy3DSpQ5pJv
  hash: 03040e0dbda5f98f3354c265dd723e0bd59071a6

**Comment by OsipXD** [comment]
Hello! 
You use wrong link for resource-pack. Link should not have redirects and should point directly to zip file with RP.

**Comment by OsipXD** [comment]
I've added tool that will help configure resource-pack.

**Comment by itsThumbsy** [comment]
I'm not sure what tool you mean

**Comment by OsipXD** [comment]
Please, wait for update

**Comment by OsipXD** [comment]
Problem resolved now?

**Comment by itsThumbsy** [comment]
I still don't know what tool you mean. But the problem is that players get
booted for not accepting the resource pack in the first place.

**Comment by OsipXD** [comment]
Lease provide your logs.

**Comment by KnifeKat** [comment]
@itsThumbsy You can disregard this issue/post if you'd like. Tuesday/Wednesday night I will be posting a massively huge update and guide to RPGInventory, that will solve this question/issue players are having as well as guide you through many other features of the Plugin that you may have a issue with understanding.

If you'd like to get the Resource pack part of the guide early to get it working, PM me(KnifeKat) on Spigot, and I will send it your way. 

Thank you in advance!

**Comment by ArronDavies** [comment]
@KnifeKat I understand that you have a tutorial ready to go soon but as @OsipXD Said he was using an incorrect URL. Here is the URL he should be using: https://cloud.endlesscode.ru/s/kJYMpy3DSpQ5pJv/download

**Comment by OsipXD** [comment]
@ArronDavies, No. Never use my cloud. Because I can change or delete RP anytime and you can't control it.

**Comment by ArronDavies** [comment]
@OsipXD Then why is it listed on the spigot page?....

Download it and re-upload it to google drive then @itsThumbsy

**Comment by OsipXD** [comment]
@ArronDavies, ehm... you can't control any link that I provide you. It doesn't matters where it placed.
This link provided only to download !examle! of resource-pack and re-upload it to own place.

**Comment by osipxd** [comment]
Closed. Create new issue if problem still here
